name: flutter_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^11.0.0
  google_fonts: ^8.0.2
  http: ^1.2.2
  shared_preferences: ^2.5.3
  get_it: ^9.2.1
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0
  intl: ^0.20.2
  table_calendar: ^3.1.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/images/logo.png
    - Assets/images/splash_bg.png
    - Assets/images/splash_bg1.png
    - Assets/images/splash_bg2.png
    - Assets/images/splash_bg6.png
    - Assets/images/splash_bg9.png
    - Assets/images/splash_bg12.png
    - Assets/images/QR.png